# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: 
  vmImage: 'ubuntu-latest'

container: mcr.microsoft.com/mlops/python:latest

steps:
    
- script: |
   pip install flake8
   pip install flake8_formatter_junit_xml
   flake8 --format junit-xml --output-file $(Build.BinariesDirectory)/flake8_report.xml --exit-zero --ignore E111
  displayName: 'Check code quality'
  
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '$(Build.BinariesDirectory)/*_report.xml'
    testRunTitle: 'Publish test results'

- task: ExtractFiles@1
  displayName: 'Extract files '
  inputs:
    destinationFolder: $(agent.builddirectory)

